### ISSUE TITLE
If use npm install, what is the minimum node version required?

### ISSUE THREAD

**Issue by shaobeichen** [Exlint/cz-vinyl#62]
This library is very well written, we hope to promote it, but I don't know the minimum node version？

**Comment by tal-rofe** [comment]
@shaobeichen 

I used this library:
https://www.npmjs.com/package/ls-engines

I got:
<img width="352" alt="Screen Shot 2022-08-21 at 22 50 26" src="https://user-images.githubusercontent.com/100444463/185808454-0e56fba2-5654-44a9-a361-c456176ca725.png">

Does it answer your Q? seems as `14.7` is the answer

**Comment by tal-rofe** [comment]
@shaobeichen 
I just checked and 12 is the minimum nodejs version supported.
