### ISSUE TITLE
Bug: After upgrading 1.4.0, the error is prompted: Could not find prompter method in the provided adapter module: cz-vinyl

### ISSUE THREAD

**Issue by shaobeichen** [Exlint/cz-vinyl#70]
### What did you do?

After upgrading 1.4.0, the error is prompted: “Could not find prompter method in the provided adapter module: cz-vinyl”, both globally and locally

### What did you expect to happen?

Can be used normally, no error message

### What actually happened?

```sh
$ npm run cz

> git-cz

Could not find prompter method in the provided adapter module: cz-vinyl
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tal-rofe** [comment]
@shaobeichen 
Fixed on version 1.4.1
