### ISSUE TITLE
request: allow for scopes to also use autocomplete prompt

### ISSUE THREAD

**Issue by jromero-pg** [Exlint/cz-vinyl#76]
### Description

Currently, only `commitType` uses autocomplete. In our monorepo, we have many scopes. It would be ideal to also be able to filter the scopes via autocomplete.

Expected user experience:
```gherkin
Given "configuration.scopes" is an array and its length is greater than 0
When the user attempts to commit
Then they should be prompted with a list of scopes
And they should be able to filter the list of scopes by typing
```

### Proposed solution

1. Change the prompt `type` from `list` to `autocomplete` here:
    https://github.com/Exlint/cz-vinyl/blob/b949ffb087e617407f768ca7c34fda8b6f9ca066/src/utils/questions.ts#L40
2. Provide a `source` to the prompt similar to how it's done with commit type:
    https://github.com/Exlint/cz-vinyl/blob/b949ffb087e617407f768ca7c34fda8b6f9ca066/src/utils/questions.ts#L32-L37

### Do you want to create a pull request?

Yes

**Comment by tal-rofe** [comment]
@jromero-pg 
Supported from version `2.1.0`
