### ISSUE TITLE
request: body format / add ticket(s) to body

### ISSUE THREAD

**Issue by jromero-pg** [Exlint/cz-vinyl#77]
### Description

The auto-detection of tickets from the branch is such a great feature. Our team would love to use it, but we would want the ticket to be a part of the body and not the header.

### Proposed solution

Allow the commit body also to be templatized like the header.

For example:

```gherkin
Given the following config:
"""
const czvinylConfig: Config = {
  headerFormat: '{type}({scope}): {subject}',
  bodyFormat: '{body}\n\nrelates to {ticketId}',
  skipTicketId: false,  
};
"""
When the user provides the following answers:
   - type: feat
   - scope: config
   - ticketId: TICKET-123
   - subject: a sample commit
   - body: longer description
Then the final commit message should be:
"""
feat(config): a sample commit

longer description

relates to TICKET-123
"""
```

I haven't fully thought through how to handle an empty `ticketId` in json format. Ideally, the line using the variable would not be present. The alternative would be a better approach for us.

### Alternatives considered

Have a new configuration field, `bodyFormat` that supports a function. The function would be fed all answers and return the final formatted body string. This would allow the implementor to be able to handle missing information gracefully.

```gherkin
Given the following config:
"""
const czvinylConfig: Config = {
  headerFormat: '{type}({scope}): {subject}',
  bodyFormat: (answers: Answers) => `${answers.body}\n\nrelates to ${answers.ticketId}`,
  skipTicketId: false,  
};
"""
When the user provides the following answers:
   - type: feat
   - scope: config
   - ticketId: TICKET-123
   - subject: a sample commit
   - body: longer description
Then the final commit message should be:
"""
feat(config): a sample commit

longer description

relates to TICKET-123
"""
```

### Do you want to create a pull request?

Yes

**Comment by tal-rofe** [comment]
@jromero-pg 
I cannot find any reason to allow a function input in the `bodyFormat` field.
Why would you expect an empty ticket ID if you ask for one in your configuration?
An empty ticket ID is not possible either way (if you ask for in the configuration..)

**Comment by jromero-pg** [comment]
In an ideal world, the ticket would be optional. The function input would allow for the handling of any optional field.

**Comment by tal-rofe** [comment]
> In an ideal world, the ticket would be optional. The function input would allow for the handling of any optional field.

So if ticket ID can be empty, the `headerFormat` should accept a function as well.
Will be released in the next minor version.
